Fix readme
Module can't work with Port (with capital letter P and without quotes). 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not parse for environment production: Syntax error at 'Port'; expected '}' at /etc/puppet/manifests/linux/kirova54/node.pp:81 on node node

Need to use 'Port' or port.